//authSupplier
export const REGISTER_SUPPLIER = 'REGISTER_SUPPLIER';
export const REGISTER_SUPPLIER_FAIL = 'REGISTER_SUPPLIER_FAIL';
export const LOGIN_SUPPLIER = 'LOGIN_SUPPLIER';
export const LOGIN_SUPPLIER_FAIL = 'LOGIN_SUPPLIER_FAIL';
export const LOAD_SUPPLIER = 'LOAD_SUPPLIER';
export const LOGOUT_SUPPLIER = 'LOGOUT_SUPPLIER';
export const AUTH_ERROR_SUPPLIER = 'AUTH_ERROR_SUPPLIER';
export const GET_CURRENT_SUPPLIER = 'GET_CURRENT_SUPPLIER';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

//searchResult
export const STATE_SEARCH = 'STATE_SEARCH';
export const NICHE_SEARCH = 'NICHE_SEARCH';
export const PRODUCT_SEARCH = 'PRODUCT_SEARCH';
export const GET_ALL_SUPPLIERS = 'GET_ALL_SUPPLIERS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const OPEN_PROFILE = 'OPEN_PROFILE';
export const ADD_FAVOURITE_SUPPLIER = 'ADD_FAVOURITE_SUPPLIER';
export const REMOVE_FAVOURITE_SUPPLIER = 'REMOVE_FAVOURITE_SUPPLIER';
export const LOAD_FAVOURITE_SUPPLIERS = 'LOAD_FAVOURITE_SUPPLIERS';
export const USERS_VISITED = 'USERS_VISITED';

//product
export const PRODUCT_ADDED = 'PRODUCT_ADDED';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const CLEAR_ALL_PRODUCTS = 'CLEAR_ALL_PRODUCTS';
export const VIEW_PRODUCT = 'VIEW_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_ALL_PRODUCTS = 'DELETE_ALL_PRODUCTS';

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL';
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';

//authUser
export const LOAD_USER = 'LOAD_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const AUTH_ERROR_USER = 'AUTH_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

//cart
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
export const RESET_CART = 'RESET_CART';

//order
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const FETCH_USER_ORDERS = 'FETCH_USER_ORDERS';
export const FETCH_SUPPLIER_ORDERS = 'FETCH_SUPPLIER_ORDERS';

export const UPDATE_PRODUCT_STATUS = 'UPDATE_PRODUCT_STATUS';
export const UPDATE_PRODUCT_STATUS_FAIL = 'UPDATE_PRODUCT_STATUS_FAIL';

//chat
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const USER_MESSAGES_READ = 'USER_MESSAGES_READ';
export const SUPPLIER_MESSAGES_READ = 'SUPPLIER_MESSAGES_READ';
export const GET_MESSAGES_USERSIDE = 'GET_MESSAGES_USERSIDE';
export const GET_MESSAGES_SUPPLIERSIDE = 'GET_MESSAGES_SUPPLIERSIDE';
